### ISSUE TITLE
Verifying commit message as well

### ISSUE THREAD

**Issue by prakashpp** [vijaykramesh/pr-lint-action#1]
First of all thank you for this action, this is really helpful. Will you accept a PR to check reference in commit message? Happy to send one.

**Comment by jedster1111** [comment]
@prakashpp Hope you don't mind but I gave this a go 😄If you want to I would definitely appreciate a review in #2

**Comment by vijaykramesh** [comment]
@prakashpp I merged @jedster1111's changes, I will close this issue but feel free to open another PR if there was something else you needed to check
