### ISSUE TITLE
v2.1 is failing inside ci

### ISSUE THREAD

**Issue by omarkhatibgg** [vijaykramesh/pr-lint-action#41]
Hey, 

thanks for this action, anyway I updated to v2.1 and it's failing. I think it's because package.json and package-lock.json are not synced.

I'm happy to provide a log if needed

Thanks
Omar

**Comment by vijaykramesh** [comment]
hey @omarkhatibco sorry this is fixed now, you can see https://github.com/vijaykramesh/pr-lint-action-example-repo/pull/2/checks for a working example, upgrade to 2.3 and you should be all good.

**Comment by omarkhatibgg** [comment]
Hey @vijaykramesh,

thank you for the quick fix and I can confirm that it's working now
